### ISSUE TITLE
site wont load through URL

### ISSUE THREAD

**Issue by yonatandaon** [tuzig/gizajs#18]
**Describe the bug**
when entering a /name through the URL it wont load and it will crash the browser
it does work when entering the life story via tuzig.com
**To Reproduce**
1. Go to www.tuzig.com/itzik 
  or bialik or anyone also /bio

**Expected behavior*
a working site

**Screenshots**
![default](https://user-images.githubusercontent.com/40161143/42420888-3e63eb26-82d5-11e8-8f06-958219abce8d.PNG)
![default](https://user-images.githubusercontent.com/40161143/42420889-3e836708-82d5-11e8-846b-806f4dbe93c8.PNG)
![default](https://user-images.githubusercontent.com/40161143/42420898-71001d48-82d5-11e8-8557-93219a326b7a.PNG)
![brave](https://user-images.githubusercontent.com/40161143/42420914-bfec6c0e-82d5-11e8-8e4a-5f7befc80649.PNG)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome, firefox, brave 

 - also incognito

**Smartphone (please complete the following information):**
 IT WORKS IN MOBILE

**Comment by daonb** [comment]
@yonatandaon please verify it's no longer a problem and close the issue
