### ISSUE TITLE
Site freezes when trying to exit a photo in /rachel

### ISSUE THREAD

**Issue by yonatandaon** [tuzig/gizajs#25]
**Describe the bug**
wenn ich entlag die rachel website und wenn ich presse ein photograph die website ist kaputt 
**To Reproduce**
1. Go to http://tuzig.com/rachel/bio
2. Click on any photo
3. try to exit the photo 
4. see error

**Expected behavior**
it should not freeze
**Screenshots**
https://mega.nz/#!ZWwUSICJ!oKIBX2Bp4kD17w8D7JqA0m_Yj-JIH3z7Y4V9Ddl6I-8
![default](https://user-images.githubusercontent.com/40161143/43137794-7be5726c-8f55-11e8-8327-13417d354d62.PNG)

**Desktop (please complete the following information):**
 the bug pressists on all browsers
and all platforms

**Comment by daonb** [comment]
Fixed
